name: RC Blog
favicon: null
layout_spectrum: 1
typography_spectrum: 0.682583722518757
title: "Romain's blog"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74600637-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b3d7fb'
    - '#d3e5fd'
    - '#75767a'
    - '#acafb4'
    - '#030303'
  brandStrength: 0.8211701752152294
  lightness: 0.8286483145784587
  saturation: 0.6736126604955643
  rhythmicContrast: 0.22233097604475915
purpose: []
